### ISSUE TITLE
Missing `darwin-arm64` when installing from `brew`

### ISSUE THREAD

**Issue by arnautov-anton** [tinygo-org/homebrew-tools#23]
[Quick install guide](https://tinygo.org/getting-started/install/macos/) does not provide information about missing support for the M1 chips so after installing `tinygo` from brew and trying to run it I get:

```
/opt/homebrew/bin/tinygo: line 2: /opt/homebrew/Cellar/tinygo/0.27.0/libexec/tinygo: Bad CPU type in executable
/opt/homebrew/bin/tinygo: line 2: /opt/homebrew/Cellar/tinygo/0.27.0/libexec/tinygo: Undefined error: 0
```
Now - I don't see the package in the releases either - are you guys planning on supporting this type of a build anytime soon?

Edit: missed [this GH issue](https://github.com/github/roadmap/issues/528) - and I see someone created separate issue in the `tinygo` repository as well - should we keep this issue open?

**Comment by aykevl** [comment]
Did you install Rosetta 2? I think you need it to run the current `tinygo` executables.

(And yes, we will eventually add Apple Silicon support but that depends on GitHub finally releasing the new macOS runners).

**Comment by arnautov-anton** [comment]
I decided to build it from source for the time being, I did not feel like installing Rosetta. Thank you though!

**Comment by aykevl** [comment]
I'm going to assume it's the lack of Rosetta 2, then.
